export type StudentProfile = {
  id: string;
  user_id: string;
  full_name: string | null;
  nickname: string | null;
  undergraduate_school: string | null;
  undergraduate_country: string | null;
  undergraduate_major: string | null;
  current_year: string | null;
  gpa: number | null;
  gpa_scale: number | null;
  ielts: number | null;
  toefl: number | null;
  gre: number | null;
  gmat: number | null;
  research_experience: string | null;
  internship_experience: string | null;
  project_experience: string | null;
  competition_experience: string | null;
  target_countries: string[] | null;
  target_majors: string[] | null;
  future_goal: string | null;
  budget_range: string | null;
  planned_entry_year: number | null;
  profile_completed: boolean | null;
  created_at: string | null;
  updated_at: string | null;
};

export type StudentProfileFormValues = {
  full_name: string;
  nickname: string;
  undergraduate_school: string;
  undergraduate_country: string;
  undergraduate_major: string;
  current_year: string;
  gpa: string;
  gpa_scale: string;
  ielts: string;
  toefl: string;
  gre: string;
  gmat: string;
  research_experience: string;
  internship_experience: string;
  project_experience: string;
  competition_experience: string;
  target_countries: string;
  target_majors: string;
  future_goal: string;
  budget_range: string;
  planned_entry_year: string;
};
